### ISSUE TITLE
How to unit test BlazorFabric?

### ISSUE THREAD

**Issue by albilaga** [BlazorFluentUI/BlazorFluentUI#140]
Hello. I want to unit test my layout that using BlazorFabric. I am using [bunit](https://github.com/egil/bunit). I already add `Services.AddBlazorFabric()` but looks lke something is still missing. [Here](https://github.com/albilaga/blazorfabrictest) is my sample project. You can see the [MainLayoutTest](https://github.com/albilaga/blazorfabrictest/blob/master/tests/blazorfabrictest.tests/MainLayoutTest.cs) especially.
Error message I get is `Object reference not set to an instance of an object.` with stacktrace
```
   at BlazorFabric.PersonaCoin.SetStyle()
   at BlazorFabric.PersonaCoin.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.UpdateRetainedChildComponent(DiffContext& diffContext, Int32 oldComponentIndex, Int32 newComponentIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Bunit.TestRenderer.AssertNoSynchronousErrors()
   at Bunit.TestRenderer.DispatchAndAssertNoSynchronousErrors(Action callback)
   at Bunit.ContainerComponent.Render(RenderFragment renderFragment)
   at Bunit.RenderedFragmentBase..ctor(ITestContext testContext, RenderFragment renderFragment)
   at Bunit.RenderedComponent`1..ctor(ITestContext testContext, RenderFragment renderFragment)
   at Bunit.RenderedComponent`1..ctor(ITestContext testContext, IReadOnlyList`1 parameters)
   at Bunit.TestContext.RenderComponent[TComponent](ComponentParameter[] parameters)
   at blazorfabrictest.tests.MainLayoutTest.Test1() in /Users/albilaga/Documents/Projects/Private/blazorfabrictest/tests/blazorfabrictest.tests/MainLayoutTest.cs:line 49
```

Notes: I also raised the question in [there](https://github.com/egil/bunit/issues/131)

**Comment by egil** [comment]
Hey folks, author of bUnit here. Let me know if you need any information regarding bUnit.

**Comment by limefrogyank** [comment]
I think it's because you're missing a `LayerHost` in your root somewhere.  In your App.razor, put the `LayerHost` as a child of `FabricTheme`.  

Anything that uses popups/modals requires a `Layer` which needs to be hosted in a `LayerHost`.  In the React components, they are using portals.  In Blazor, we're not doing that (because there are no portals) but we're mimicking them with the eventual intention of similar functionality.  Currently we do not have the functionality of portals and we can only define one host... but perhaps we can enable that in the future.

`Persona` uses `Tooltip` which requires a `Callout` which uses `Layer`.

**Comment by limefrogyank** [comment]
As for unit testing... as a non-professional programmer, I have never been forced to do unit tests.  I understand the concept but I have never found the motivation to learn it. 😅

If this is something you want to help us with, be my guest!  We accept pull requests from anyone.

**Comment by egil** [comment]
Hehe well, the point of writing test is not to please a manager, it's to make it easier to maintain your library in the long eun. And once you get learn how to do it well, you are likely to be done faster with your work than without.

When I do TDD I usually spent very little time debugging, which can otherwise take quite a bit of time.

As to the question from @albilaga, what I gather is that there needs to be a bunch of components higher up the render tree, besides the necessary services registered?

**Comment by albilaga** [comment]
Tried to add `LayerHost` in `App.razor` and still not working, If you see in [MainLayout](https://github.com/albilaga/blazorfabrictest/blob/master/Client/Shared/MainLayout.razor) actually I already add `LayerHost` in there. And notes this is happening on unit test project only. Run project directly in blazor it is working fine. My thoughts is be cause I can't declare 
```
builder.RootComponents.Add<GlobalRules>("#staticcs");
```
in the unit test? Or also maybe css files also?

**Comment by limefrogyank** [comment]
Ok, so I think there must be something missing in the test setup.  I read a little of the C# testing for bUnit and it said that some injected services may need to be mock services.  I wasn't sure if parameters all work in testing, especially the CascadingValues.

All I can see in the `SetStyle` method of Persona.razor that *might* be null is the `Theme` variable.  This is set in the FabricTheme component on the injected `ThemeProvider` and then set as a CascadingVariable to be picked up by the base component (`FabricBaseComponent`) for all components in this library.

**Comment by albilaga** [comment]
So what I need to pass is `Theme` or `ThemeProvider`? In `bunit` we can pass cascading parameter like this
```
var mainLayout = RenderComponent<MainLayout>(ComponentParameter.CreateCascadingValue($"{nameOfParameter}",value);
```
But I am not sure what to pass in there?

**Comment by limefrogyank** [comment]
I think `Theme` is the big one that's missing.  (Like I said, I don't know much about bUnit so this is a guess.)

You somehow need to provide a CascadingValue called `Theme` of type `ITheme` to all child components.  

You can create the instance by injecting (or just constructing) `ThemeProvider` and retreiving the `Theme` variable inside.  It automatically makes a light-mode theme.
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFabric.Theme/ThemeProvider.cs

**Comment by albilaga** [comment]
Ok. This is looks like working
```
var mainLayout = RenderComponent<MainLayout>(ComponentParameter.CreateCascadingValue("Theme",new ThemeProvider().Theme));
```
But I also need to add `Services.AddSingleton<IComponentStyle>(new ComponentStyle { GlobalCSSheets = new ObservableCollection<IGlobalCSSheet>() });`

Thanks for your help @egil and @limefrogyank . Really appreciate it. Now I need to finish my unit test :D Will ask again if I need more help

**Comment by egil** [comment]
Awesome @albilaga, glad it worked out.

For others who want to write tests and are using BlazorFluentUI, can you please share the complete test setup, so others might benefit?

Ps. passing a CascadingValue to the RenderComponent method can be shortened a bit, like so:

```c#
var mainLayout = RenderComponent<MainLayout>(
    CascadingValue("Theme", new ThemeProvider().Theme)
);
```

**Comment by Purendra-naik-ascendlearning-com** [comment]
I have similar problem to stub the cascading param 
[CascadingParameter]
public IType State { private get; init; }

var component1 = ctx.RenderComponent<ChatDialog>(ComponentParameter.CreateCascadingValue("State", convoState));  // not working
var component2 = ctx.RenderComponent<ChatDialog>(CascadingValue("State", convoState));  // not working

var component = ctx.RenderComponent<ChatDialog>(parameters => parameters
	 .Add(p => p.State, convoState)                      
   );           // Not able to access p.State as it is protected
