### ISSUE TITLE
BFUPanel doesn't work on Blazor Server

### ISSUE THREAD

**Issue by volkan-a** [BlazorFluentUI/BlazorFluentUI#160]
Panel is showing up well. However it gives an error when I try to dismiss.

```
Error: Microsoft.JSInterop.JSException: Could not find 'BlazorFabricPanel' in 'window'.
Error: Could not find 'BlazorFabricPanel' in 'window'.
    at https://localhost:5001/_framework/blazor.server.js:8:30748
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.server.js:8:30709)
    at https://localhost:5001/_framework/blazor.server.js:8:31416
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:31390)
    at https://localhost:5001/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:17165)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorFluentUI.BFUPanel.SetRegistrationsAsync()
   at BlazorFluentUI.BFUPanel.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by limefrogyank** [comment]
@volkan-a Yeah, i found that one and i think it's fixed. We just have to push a new nuget package. Sorry about the bug. New package tomorrow morning probably.

**Comment by limefrogyank** [comment]
Fixed here: https://github.com/BlazorFluentUI/BlazorFluentUI/commit/24710ce891fb4b22c9ce324642051ddb001c218a
