### ISSUE TITLE
Followed through your setup steps and got this exception.

### ISSUE THREAD

**Issue by markmercer10** [BlazorFluentUI/BlazorFluentUI#178]
Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorFluentUI.BFUDatePicker.CreateGlobalCss(ITheme theme)
   at BlazorFluentUI.BFUDatePicker.<BuildRenderTree>b__163_0()
   at BlazorFluentUI.ComponentStyle.AddOneStyleSheet(IGlobalCSSheet sheet)
   at BlazorFluentUI.ComponentStyle.CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at BlazorFluentUI.BFUGlobalCS.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

**Comment by markmercer10** [comment]
In step 5 it says
You may need to add an @using BlazorFluentUI to the top of your _Hosts.cshmtl to avoid a 'GlobalRules could not be found` error.

I did that, still getting that error.

**Comment by markmercer10** [comment]
I had to add @using BlazorFabric to get that to work.

Finally got application to compile, I see the DatePicker but clicking on it does nothing

**Comment by markmercer10** [comment]
I also notice that inside the <BFULayerHost> tag all the content is left justified.

**Comment by markmercer10** [comment]
Thanks for all the help

**Comment by limefrogyank** [comment]
Sorry!  I was gone all weekend... did you get help from the Telegram channel by any chance?  

If you're using  `_Hosts.cshtml` then you're doing server-side blazor?  If not, then you may have missed a client-side blazor step.
As far as I remember, the files you need to adjust for client-side blazor are:
  
Program.cs (AddBlazorFluentUI and Add<BFUGlobalRules>)
App.razor (BFUTheme & BFULayoutHost)
index.html (js file, css file, and style tag)
_Imports.razor (@using BlazorFluentUI)

For server-side, there are slight differences in the Program.cs file and the _Host.cshtml (instead of index.html)

**Comment by vnbaaij** [comment]
Closed because of no activity for a long time. ALso, instructions have probably changed since then.
