### ISSUE TITLE
BlazorFluentUI.AllComponents won't work without System.CodeDom and other nuget packages

### ISSUE THREAD

**Issue by PhilippSonntagORGADATA** [BlazorFluentUI/BlazorFluentUI#195]
Hello there,

I want to report an error I've got after updating from **v3.1.2** or lower to any higher version.
After the update I've got exceptions while loading the page. I had to install missing dependencies which resulted in 4
unnecessary nuget packages I added to make BFU work.

### The app won't work without any of those packages:
- `System.CodeDom v4.7`
- `System.IO.Ports v4.7`
- `System.Diagnostics.PerformanceCounter v4.7`
- `System.Threading.AccessControl v4.7`

### The exception in the browser console is always the same:
``
Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at BlazorFluentUI.BFUStylePreloader.GetTypesFromAssemblies(Assembly assembly)
   at BlazorFluentUI.BFUStylePreloader.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
``

### My environment:
- .NET Core 3.1.301
- VS 2019 16.6.3
- BlazorFluentUI.AllComponents 3.1.5
- Blazor Serverside

All in all thank you for the possibility to use Fluent in Blazor. I hope this issue gives you enough information :)

**Comment by limefrogyank** [comment]
That's really odd because there is no way we would ever need access to `System.IO.Ports`.   That's for serial ports!  I don't think we have ever used System.CodeDom nor System.Diagnostics.PerformanceCounter.  

System.Threading.AccessControl is unlikely, too.  Even though you're using ServerSide, our code also targets ClientSide and there's no threading in clientside (yet).

I think there may be another package that is conflicting.  I tried to create a blank project from and followed our wiki to setup BlazorFluentUI for server-side and it works fine on my end.

**Comment by limefrogyank** [comment]
Perhaps you are pointing to the wrong assembly for the StylePreloader.  
Can you try:
```
<BlazorFluentUI.BFUStylePreloader AppAssembly="@typeof(Program).Assembly" LoadAllComponents="true" />
```

**Comment by PhilippSonntagORGADATA** [comment]
Thanks for the fast answer. I tried the code snippet, but it didn't brought any changes as the previous state was very similar. 
After that I've created a new project where I used exactly the same nuget packages. It works like a charm.

I don't think that this is an error within your project, so I'm going to look for a place where this exception could come from.

Issue closed ^^
