### ISSUE TITLE
Trouble with Unit Testing BFUCommandBar

### ISSUE THREAD

**Issue by natesevn** [BlazorFluentUI/BlazorFluentUI#199]
Hello. I'm trying to add a [bunit](https://github.com/egil/bunit) unit test to verify that the list of buttons rendered by BFUCommandBar is correct but I'm running into some issues. Here is my error message:

``` 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Bunit.Rendering.TestRenderer.AssertNoUnhandledExceptions()
at Bunit.Rendering.TestRenderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
at Bunit.GeneralEventDispatchExtensions.TriggerEventAsync(IElement element, String eventName, EventArgs eventArgs)
at Bunit.MouseEventDispatchExtensions.ClickAsync(IElement element, MouseEventArgs eventArgs)
at Bunit.MouseEventDispatchExtensions.Click(IElement element, Int64 detail, Double screenX, Double screenY, Double clientX, Double clientY, Int64 button, Int64 buttons, Boolean ctrlKey, Boolean shiftKey, Boolean altKey, Boolean metaKey, String type)
at ObjectProfileTests.ObjectProfile_GivenARole_CorrectCommandButtonsAreShown(String authPolicy, String[] expectedButtons) 
```

and my inner stack trace:
```
at BlazorFluentUI.BFUResizeGroup`1.<OnAfterRenderAsync>d__59.MoveNext()
```

The component under test is a button that, when clicked, renders a BFUCommandBar component. This exception arises when I try to simulate the click using bunit. 

I've tried following the recommendations here: #140 (i.e. including `LayerHost`, passing `Theme` as a cascading param). 

Thanks in advance.

**Comment by limefrogyank** [comment]
I don't know the specifics of bunit unit testing, but in general, unit tests don't draw any UI when they test the logic.  If there is an error within BFUResizeGroup, then it might have something to do with measuring the size of the container.  BFUResizeGroup has to know how many buttons to display in the main area and how many to put in the overflow area.  It does that by measuring the available width.  

I honestly don't know what happens if the measurement can't be performed.  There are a lot of checks for whether a measurement isNaN... but there may not be enough.

**Comment by natesevn** [comment]
I see, that makes sense, thanks. 

One thing I tried doing was catching the BFUResizeGroup exception and ignoring it so the test can proceed. I found that the markup generated by the tests still contained the buttons generated by the BFUCommandBar component, so I'm guessing this would suffice as a workaround for now. Will try to perform more tests and update if I notice anything else.
