### ISSUE TITLE
Issue on .NET 5 RC1

### ISSUE THREAD

**Issue by hez2010** [BlazorFluentUI/BlazorFluentUI#209]
Client app.

App.razor:
```razor
<BFUTheme>
    <BFUStylePreloader AppAssembly="typeof(MainLayout).Assembly" LoadAllComponents=true />
    <BFULayerHost>
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                    <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            </Found>
            <NotFound>
                    <LayoutView Layout="@typeof(MainLayout)">
                            <p>Sorry, there's nothing at this address.</p>
                    </LayoutView>
            </NotFound>
        </Router>
    </BFULayerHost>
</BFUTheme>
```

```none
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: 
System.IO.FileNotFoundException: 
File name: 'System.Runtime.InteropServices.WindowsRuntime'
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at BlazorFluentUI.BFUStylePreloader.GetTypesFromAssemblies(Assembly assembly)
   at BlazorFluentUI.BFUStylePreloader.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

**Comment by limefrogyank** [comment]
I haven't tried this yet myself.  We are in the process of updating the components to NET5 to take advantage of the new functionality though.  

As a workaround, take out the  `BFUStylePreloader`.  It's only needed to preload styles for components that haven't optimized yet.  I don't think much will change... and when we get the new components updated, everything will be much faster anyways.  We won't be using this StylePreloader component at all.

(For example, in BFUDropdown, the component itself has a BFUStylePreloader that preloads the styles for a BFUCallout because that doesn't get created until you click the dropdown.)

**Comment by NPadrutt** [comment]
I can confirm that the work around works.

**Comment by geffzhang** [comment]
on .NET 5 RC2
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorFluentUI.BFUStylePreloader.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by limefrogyank** [comment]
We're going to release a full .NET5 version of this library when .NET5 is finally released.  It's practically ready and won't contain StylePreloader anymore.  In the meantime, avoid using StylePreloader when using NET5.  It's only used to speed component style loading and not critical.

Maybe when all the style bugs are fixed, I can release a preview nuget package.
