### ISSUE TITLE
Integrating BlazorFluentUI  Datalist into  Blazor WebAssembly using .net5.0

### ISSUE THREAD

**Issue by ssuttonDev** [BlazorFluentUI/BlazorFluentUI#269]
Hello,
 
   I am having problem try to run the application when I am trying to added a data list.   On my razor component page  I have the following base on your sample code 

<div style="height:600px;" data-is-scrollable>
    <BFUStack Style="height:100%;">
        <h3>Available Document Type</h3>
        <BFUDetailsList ItemsSource="InputList"
                        Columns="Columns"
                        GetKey=@(item=>item.Key)
                        LayoutMode="DetailsListLayoutMode.Justified"
                        TItem="DataItem"
                        OnItemInvoked="OnClick"
                        _Selection="selection"_
                        SelectionMode="SelectionMode.Multiple">
        </BFUDetailsList>
    </BFUStack>
</div>
@code {

    List<DataItem> InputList = new List<DataItem>();
    _Selection<DataItem> selection = new Selection<DataItem>();_

    public List<BFUDetailsRowColumn<DataItem>> Columns = new List<BFUDetailsRowColumn<DataItem>>();

    private void OnColumnClick(BFUDetailsRowColumn<DataItem> column)
    {
        // since we're creating a new list, we need to make a copy of what was previously selected
        // var selected = selection.GetSelection();

        //create new sorted list
        // InputList = new List<DataItem>(column.IsSorted ? InputList.OrderBy(x => x.DisplayName) : InputList.OrderByDescending(x => x.DisplayName));

        //clear old selection and create new selection
        //selection.SetKeySelected(selected, true);

        column.IsSorted = !column.IsSorted;
        StateHasChanged();
    }

    protected override void OnInitialized()
    {
       // selection.GetKey = (item => item.Key);
        Columns.Add(new BFUDetailsRowColumn<DataItem>("DocumentType", x => x.ClassType) { MaxWidth = 70, Index = 0 });
        Columns.Add(new BFUDetailsRowColumn<DataItem>("Confidence", x => x.Confidence) { Index = 1, MaxWidth = 150, OnColumnClick = this.OnColumnClick, IsResizable = true });

        int count = 0;
        for (var i = 0; i < 1000; i++)
        {
            count++;

            InputList.Add(new DataItem("test"));
        }

        base.OnInitialized();
    }

When I try to run it I get the following error:

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not find method '.ctor' due to a type load error: Could not load type of field 'BlazorFluentUI.Selection`1[TItem]:selectionChanged' (5) due to: Could not load file or assembly 'System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. assembly:BlazorFluentUI.BFUSelectionZone.dll type:Selection`1 member:(null)
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type componentType)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

It has something to do with the selection and System.Reactive, which I have loaded the updated version into the project.  Is there something I am over looking.  Thanks for any help

**Comment by limefrogyank** [comment]
System.Reactive should load as part of the BFUBaseComponent package:
![image](https://user-images.githubusercontent.com/7821384/110876721-edb49800-828c-11eb-9e47-2e5bf26f7413.png)

There shouldn't be a newer version than 5.0.0 and you shouldn't have to load it manually.  I'm not sure what else could be wrong...

**Comment by ssuttonDev** [comment]
It seem the packages only reference to system.reactive.xml, but the system.reactive.dll is missing from the package for version 5.5.0. . Had to manually add the .dll from the 4.3.2 version for it to work.
