### ISSUE TITLE
Cannot read property 'scrollHeight' of null

### ISSUE THREAD

**Issue by SSgumS** [BlazorFluentUI/BlazorFluentUI#275]
Sometimes on initialization of page I encounter this error:

    crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
          Unhandled exception rendering component: Cannot read property 'scrollHeight' of null
          TypeError: Cannot read property 'scrollHeight' of null
              at Object.e.measureScrollDimensions (https://localhost:44393/_content/BlazorFluentUI.BFUBaseComponent/blazorFluentUi.min.js:1:2718)
              at https://localhost:44393/_framework/blazor.webassembly.js:1:3942
              at new Promise (<anonymous>)
              at Object.beginInvokeJSFromDotNet (https://localhost:44393/_framework/blazor.webassembly.js:1:3908)
              at Object.w [as invokeJSFromDotNet] (https://localhost:44393/_framework/blazor.webassembly.js:1:64232)
              at _mono_wasm_invoke_js_blazor (https://localhost:44393/_framework/dotnet.5.0.3.js:1:190800)
              at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
              at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
              at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
              at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
    Microsoft.JSInterop.JSException: Cannot read property 'scrollHeight' of null
    TypeError: Cannot read property 'scrollHeight' of null
        at Object.e.measureScrollDimensions (https://localhost:44393/_content/BlazorFluentUI.BFUBaseComponent/blazorFluentUi.min.js:1:2718)
        at https://localhost:44393/_framework/blazor.webassembly.js:1:3942
        at new Promise (<anonymous>)
        at Object.beginInvokeJSFromDotNet (https://localhost:44393/_framework/blazor.webassembly.js:1:3908)
        at Object.w [as invokeJSFromDotNet] (https://localhost:44393/_framework/blazor.webassembly.js:1:64232)
        at _mono_wasm_invoke_js_blazor (https://localhost:44393/_framework/dotnet.5.0.3.js:1:190800)
        at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
        at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
        at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
        at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
       at BlazorFluentUI.BFUResizeGroup`1.<GetElementDimensionsAsync>d__60[[BlazorFluentUI.BFUCommandBarInternal.BFUCommandBarData, BlazorFluentUI.BFUCommandBar, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
       at BlazorFluentUI.BFUResizeGroup`1.<GetNextStateAsync>d__62[[BlazorFluentUI.BFUCommandBarInternal.BFUCommandBarData, BlazorFluentUI.BFUCommandBar, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
       at BlazorFluentUI.BFUResizeGroup`1.<OnAfterRenderAsync>d__59[[BlazorFluentUI.BFUCommandBarInternal.BFUCommandBarData, BlazorFluentUI.BFUCommandBar, Version=4.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
       at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
    d.printErr @ blazor.webassembly.js:1

**Comment by vnbaaij** [comment]
Can't get it reproduced in V5. Please re-open if you still see it and add some details on which page it happens and other relevant details.
