### ISSUE TITLE
'FluentUIBaseComponent' was undefined

### ISSUE THREAD

**Issue by Tailslide** [BlazorFluentUI/BlazorFluentUI#278]
I followed the instructions for setting up on blazor webassembly using 5.0.0-CI-20210324-140406
I get this message when I run:

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'FluentUIBaseComponent.initializeFocusRects' ('FluentUIBaseComponent' was undefined).
      Error: Could not find 'FluentUIBaseComponent.initializeFocusRects' ('FluentUIBaseComponent' was undefined).
          at https://localhost:44385/_framework/blazor.webassembly.js:1:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (https://localhost:44385/_framework/blazor.webassembly.js:1:1247)
          at b (https://localhost:44385/_framework/blazor.webassembly.js:1:2989)
          at https://localhost:44385/_framework/blazor.webassembly.js:1:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44385/_framework/blazor.webassembly.js:1:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44385/_framework/blazor.webassembly.js:1:64232)
          at _mono_wasm_invoke_js_blazor (https://localhost:44385/_framework/dotnet.5.0.3.js:1:190800)
          at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)

**Comment by Tailslide** [comment]
Nevermind.. it was a caching issue

**Comment by vnbaaij** [comment]
Was just about to start a new WebAssemly project to test. Couldn't reproduce in Blazor Server app

**Comment by Tailslide** [comment]
Sorry about that.. Shift-F5 solved my problems.  I seem to have that issue sometimes debugging blazor stuff.
