### ISSUE TITLE
Dropdown stopped working inside the panel component after 5.0 update

### ISSUE THREAD

**Issue by Cobra86** [BlazorFluentUI/BlazorFluentUI#295]
The dropdown and callout components stopped working inside the panel component. 
I clicked on the dropdown and it did nothing.

**Comment by Cobra86** [comment]
Dropdown Update:
its working on the demo website and I've created new project and tested it and its working fine but I'm getting the error below when i click on the dropdown more than once.

Exception: 
Microsoft.JSInterop.JSException: Cannot read property 'ownerDocument' of null
TypeError: Cannot read property 'ownerDocument' of null
    at Module.registerHandlers (https://localhost:44318/_content/BlazorFluentUI.CoreComponents/callout.js:2:32)
    at https://localhost:44318/_framework/blazor.server.js:1:70045
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44318/_framework/blazor.server.js:1:70011)
    at https://localhost:44318/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44318/_framework/blazor.server.js:1:26263)
    at e.processIncomingData (https://localhost:44318/_framework/blazor.server.js:1:24201)
    at e.connection.onreceive (https://localhost:44318/_framework/blazor.server.js:1:17286)
    at WebSocket.i.onmessage (https://localhost:44318/_framework/blazor.server.js:1:46503)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at BlazorFluentUI.CalloutContent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by Cobra86** [comment]
Sorry, I've fixed the issue, there was conflict with my css and js codes.

**Comment by vnbaaij** [comment]
Good you have it solved. There was however a problem in the `registerHandlers` function where the `targetElement` had a null value sometimes (where the `ownerDocument` is a property of) . I already changed it in my local branch but not committed it yet. Will be in V5.2.3
