### ISSUE TITLE
Unit Testing BFU Dropdown Component

### ISSUE THREAD

**Issue by chchadha** [BlazorFluentUI/BlazorFluentUI#313]
Hello, 

I am using BUnit to test the state of a razor page. However, during tests the BFU dropdown component throws a null exception when trying to render the component. The exception occurs when the BFU dropdown attempts to SetStyle() in the OnInitalizedAsync method. Thanks in advance :) 

Reference: https://github.com/BlazorFluentUI/BlazorFluentUI/issues/140
 
I've provided a stack trace below:

```
at BlazorFluentUI.Dropdown.SetStyle()
   at BlazorFluentUI.Dropdown.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Bunit.Rendering.TestRenderer.AssertNoUnhandledExceptions() in /_/src/bunit.core/Rendering/TestRenderer.cs:line 280
   at Bunit.Rendering.TestRenderer.Render[TResult](RenderFragment renderFragment, Func`2 activator) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 164
   at Bunit.Rendering.TestRenderer.RenderFragment(RenderFragment renderFragment) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 38
   at Bunit.Extensions.TestContextExtensions.RenderInsideRenderTree[TComponent](TestContextBase testContext, RenderFragment renderFragment) in /_/src/bunit.web/Extensions/TestContextExtensions.cs:line 20
   at Bunit.TestContext.Render[TComponent](RenderFragment renderFragment) in /_/src/bunit.web/TestContext.cs:line 61
   at Bunit.TestContext.RenderComponent[TComponent](ComponentParameter[] parameters) in /_/src/bunit.web/TestContext.cs:line 36
```

**After adding CascadingParameter for BFU theme (suggestion provided in other issue. SetStyle() method relies on the theme to set css properties).** 

**Code Change** `  host.RenderComponent<COMPONENT>(ComponentParameter.CreateCascadingValue("Theme", new ThemeProvider().Theme));'

**Resulting Call Trace:** 
```
BlazorFluentUI.ResponsiveComponentBase.OnAfterRenderAsync(Boolean firstRender)
   at BlazorFluentUI.Dropdown.OnAfterRenderAsync(Boolean firstRender)
   at Bunit.Rendering.TestRenderer.AssertNoUnhandledExceptions() in /_/src/bunit.core/Rendering/TestRenderer.cs:line 276
   at Bunit.Rendering.TestRenderer.Render[TResult](RenderFragment renderFragment, Func`2 activator) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 164
   at Bunit.Rendering.TestRenderer.RenderFragment(RenderFragment renderFragment) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 38
   at Bunit.Extensions.TestContextExtensions.RenderInsideRenderTree[TComponent](TestContextBase testContext, RenderFragment renderFragment) in /_/src/bunit.web/Extensions/TestContextExtensions.cs:line 20
   at Bunit.TestContext.Render[TComponent](RenderFragment renderFragment) in /_/src/bunit.web/TestContext.cs:line 61
   at Bunit.TestContext.RenderComponent[TComponent](ComponentParameter[] parameters) in /_/src/bunit.web/TestContext.cs:line 36
```

**BFU Implementation:** 
  ```
<Dropdown Label="Dropdown"
                      ItemsSource=@(Items)
                      Placeholder="Select an item"
                      OnChange="@((a) => SelectedItem = a.Option)"/>
```

**Comment by vnbaaij** [comment]
Hi, missing some context here. As you describe, a theme is needed. Do you have that [setup](https://github.com/BlazorFluentUI/BlazorFluentUI/wiki/How-To-Use:-Blazor-Server#add-themes)?

You don't need the `CascadingParameter` as the `Dropdown` implements `FluentUIBaseComponent` which already gives you access to the theme.

**Comment by chchadha** [comment]
Hi, thanks for the response. I do have the BlazorFluent UI theme setup on the App.razor
```
<BlazorFluentUI.Theme>
    <CascadingAuthenticationState>
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
        <BlazorFluentUI.LayerHost/>
    </CascadingAuthenticationState>
</BlazorFluentUI.Theme>
```

**Comment by limefrogyank** [comment]
Do the unit tests use the `builder.Services.AddBlazorFluentUI();` line in `Program.cs`?

I'm assuming probably not.  I think you'll need to add at least the `ThemeProvider` service like we do inside the extension:https://github.com/BlazorFluentUI/BlazorFluentUI/blob/main/src/BlazorFluentUI.CoreComponents/BaseComponent/Extensions/ServiceExtension.cs#L10

The `ThemeProvider` is what contains all the C# theme defaults.  It may be a bit outdated since it might be better to use the global css variables instead... but I believe that's what's missing.

**Comment by chchadha** [comment]
Hi, thanks for the response. Originally I was using version 5.0.1. I had upgraded to the latest (5.28). The testing project and Blazor project both have the BFU dependency added. I've also added the scoped dependency for the ThemeProvider in the test project. 
I've removed added the cascading value as previously mentioned. However, the dropdown issue still persists. I receive the following null exception when trying to test:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=BlazorFluentUI.CoreComponents
  StackTrace:
   at BlazorFluentUI.ResponsiveComponentBase.<OnAfterRenderAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at BlazorFluentUI.Dropdown.<OnAfterRenderAsync>d__117.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Bunit.Rendering.TestRenderer.AssertNoUnhandledExceptions() in /_/src/bunit.core/Rendering/TestRenderer.cs:line 283
   at Bunit.Rendering.TestRenderer.Render[TResult](RenderFragment renderFragment, Func`2 activator) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 166
   at Bunit.Rendering.TestRenderer.RenderFragment(RenderFragment renderFragment) in /_/src/bunit.core/Rendering/TestRenderer.cs:line 38
   at Bunit.Extensions.TestContextExtensions.RenderInsideRenderTree[TComponent](TestContextBase testContext, RenderFragment renderFragment) in /_/src/bunit.web/Extensions/TestContextExtensions.cs:line 20
   at Bunit.TestContext.Render[TComponent](RenderFragment renderFragment) in /_/src/bunit.web/TestContext.cs:line 61
   at Bunit.TestContext.RenderComponent[TComponent](ComponentParameter[] parameters) in /_/src/bunit.web/TestContext.cs:line 36

```


When I remove the dropdown components from my razor page, testing works as expected. Thanks for the help!

**Comment by vnbaaij** [comment]
Can you provide a bit more context on what kind of code you have in the test project (or more specific in the page you are testing)? I don't have expereince with BUnit (yet). Also can you gather from debugging the error what object reference is not set?

**Comment by vnbaaij** [comment]
Closed due to inactivity
