### ISSUE TITLE
Uncaught (in promise) Error, when loading Panel onClick of IconButton.

### ISSUE THREAD

**Issue by luzan** [BlazorFluentUI/BlazorFluentUI#322]
I am trying to display a panel from BlazorFluentUI but when clicked on IconButton on the header component. I keep getting Uncaught (in promise) Error and couldn't track back to what's causing this error or how may I solve it.
I was previously using Version 5.2.0, but also could recreate it on 5.3.1

I created a very simple project to recreate, I have followed the Instruction on [How To Use: Blazor WebAssembly ](https://github.com/BlazorFluentUI/BlazorFluentUI/wiki/How-To-Use:-Blazor-WebAssembly)

You may clone this repo to reproduce : https://github.com/luzan/DemoFluentUI

Here's the Error Message as is on Developer Console
```
Uncaught (in promise) Error: Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to System.Double. Path: $ | LineNumber: 0 | BytePositionInLine: 4.. See InnerException for more details.
     ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Double. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
     ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
       at System.Text.Json.Utf8JsonReader.TryGetDouble(Double& value)
       at System.Text.Json.Utf8JsonReader.GetDouble()
       at System.Text.Json.Serialization.Converters.DoubleConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
       at System.Text.Json.Serialization.JsonConverter`1[[System.Double, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Double& value)
       at System.Text.Json.Serialization.JsonConverter`1[[System.Double, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=456asdfadf765fr]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
       --- End of inner exception stack trace ---
       at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
       at System.Text.Json.Serialization.JsonConverter`1[[System.Double, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=456asdfadf765fr]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
       at System.Text.Json.Serialization.JsonConverter`1[[System.Double, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=456asdfadf765fr]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
       at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
       at System.Text.Json.JsonSerializer.ReadValueCore[Object](JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
       at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
       at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
       --- End of inner exception stack trace ---
       at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Double, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
       at BlazorFluentUI.Panel.UpdateFooterPositionAsync()
        at Object.endInvokeDotNetFromJS (https://localhost:5001/_framework/blazor.webassembly.js:1:4191)
        at Object.invokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3797)
        at Object.w [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:64301)
        at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.5.0.5.js:1:190800)
        at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
        at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
        at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
        at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
        at mono_jit_runtime_invoke (<anonymous>:wasm-function[7347]:0x118e5f)
        at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d42)
```

  [1]: https://www.blazorfluentui.net/PanelPage

**Comment by Matthewsre** [comment]
For some more context, I Just spoke with another colleague of mine that has been experiencing the same issue since upgrading to a javascript isolation version. I just switched from 5.0.1 to 5.3.1 that starting having this issue.

**Comment by vnbaaij** [comment]
Extra checks are added in getClientHeight and getScrollHeight so they return 0 when and invalid element is used.

When running the Demo.Server sample after applying these changes and replacing the contents of the Demo.Sever `MainLayout.razor` with your `MainLayout.razor`, clicking the waffle shows a panel without errors.

The changes will be part of the 5.3.2 release
