### ISSUE TITLE
Ribbon in Blazor Server issues

### ISSUE THREAD

**Issue by johngsandiford** [BlazorFluentUI/BlazorFluentUI#333]
Hi, looks like a great project.  

I am having issues with the Ribbon in server side Blazor.  

There are a few different errors that I get, and these can be reproduced using the sample server side project for a short while, resulting in fatal connection errors.  Just hover over buttons, click, change tabs etc... and it usually has a fatal error within 30 secs crashing the app.

Error 1 that I commonly encounter:

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'JSObjectReference'.
   at Microsoft.JSInterop.Implementation.JSObjectReference.ThrowIfDisposed()
   at Microsoft.JSInterop.Implementation.JSObjectReference.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeAsync[TValue](IJSObjectReference jsObjectReference, String identifier, CancellationToken cancellationToken, Object[] args)
   at BlazorFluentUI.CalloutContent.CalculateCalloutPositionAsync(CancellationToken cancellationToken)
   at BlazorFluentUI.CalloutContent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

Error 2 that I commonly encounter:

Microsoft.JSInterop.JSException: Cannot read property 'dataset' of null
TypeError: Cannot read property 'dataset' of null
    at Module.addOrUpdateVirtualParent

If you can't reproduce, I can try and provide more info with guidance, but it happens consistently for me.

Thanks, John

**Comment by vnbaaij** [comment]
Hi, 

I'm not seeing any of these issues when I run the server demo on my local machine. If this is an implementation in a new project, I would suggest you go through the [server setup instructions again](https://github.com/BlazorFluentUI/BlazorFluentUI/wiki/How-To-Use:-Blazor-Server). My guess is you skipped one of the necessary step (as I have myself before as well :)). Maybe also comapare your setup to the pages/components in the demo site.

**Comment by johngsandiford** [comment]
Hi, these errors occur using the BlazorFluentUI ribbon server demo (see attached image).  It can take a little while to trigger the errors.  

![ribbon-issue](https://user-images.githubusercontent.com/8300961/123521966-fac98b80-d6b1-11eb-9333-6d163f182692.gif)
